export const ARTICLES_LIST_REQUEST = "ARTICLES_LIST_REQUEST";
export const ARTICLES_LIST_SUCCESS = "ARTICLES_LIST_SUCCESS";
export const ARTICLES_LIST_FAIL = "ARTICLES_LIST_FAIL";

export const ARTICLES_ADD_REQUEST = "ARTICLES_ADD_REQUEST";
export const ARTICLES_ADD_SUCCESS = "ARTICLES_ADD_SUCCESS";
export const ARTICLES_ADD_FAIL = "ARTICLES_ADD_FAIL";

export const ARTICLES_DETAILS_REQUEST = "ARTICLES_DETAILS_REQUEST";
export const ARTICLES_DETAILS_SUCCESS = "ARTICLES_DETAILS_SUCCESS";
export const ARTICLES_DETAILS_FAIL = "ARTICLES_DETAILS_FAIL";

export const ARTICLES_UPDATE_REQUEST = "ARTICLES_UPDATE_REQUEST";
export const ARTICLES_UPDATE_SUCCESS = "ARTICLES_UPDATE_SUCCESS ";
export const ARTICLES_UPDATE_FAIL = "ARTICLES_UPDATE_FAIL";
