export const CART_ADD_ITEM = "CART_ADD_ITEM";

export const CART_REMOVE_ITEMS = "CART_REMOVE_ITEMS";
export const CART_REMOVE_SINGLE_ITEM = "CART_REMOVE_SINGLE_ITEM";

export const CART_SHIPPING_CREATE = "CART_SHIPPING_CREATE";
export const CART_SHIPPING_REMOVE = "CART_SHIPPING_REMOVE";
