export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_LIST_BY_STATUS_REQUEST = "ORDER_LIST_BY_STATUS_REQUEST";
export const ORDER_LIST_BY_STATUS_SUCCESS = "ORDER_LIST_BY_STATUS_SUCCESS";
export const ORDER_LIST_BY_STATUS_FAIL = "ORDER_LIST_BY_STATUS_FAIL";
export const ORDER_LIST_BY_STATUS_REFRESH = "ORDER_LIST_BY_STATUS_REFRESH";

export const ORDER_STATUS_CHANGE_REQUEST = "ORDER_STATUS_CHANGE_REQUEST";
export const ORDER_STATUS_CHANGE_SUCCESS = "ORDER_STATUS_CHANGE_SUCCESS";
export const ORDER_STATUS_CHANGE_FAIL = "ORDER_STATUS_CHANGE_FAIL";

export const ORDER_LIST_BY_USER_REQUEST = "ORDER_LIST_BY_USER_REQUEST";
export const ORDER_LIST_BY_USER_SUCCESS = "ORDER_LIST_BY_USER_SUCCESS";
export const ORDER_LIST_BY_USER_FAIL = "ORDER_LIST_BY_USER_FAIL";
