export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_COMMENT_REQUEST = "PRODUCT_COMMENT_REQUEST";
export const PRODUCT_COMMENT_SUCCESS = "PRODUCT_COMMENT_SUCCESS";
export const PRODUCT_COMMENT_FAIL = "PRODUCT_COMMENT_FAIL";

export const PRODUCT_COMMENT_DELETE = "PRODUCT_COMMENT_DELETE";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";

export const FAVORITE_LIST_REQUEST = "FAVORITE_LIST_REQUEST";
export const FAVORITE_LIST_SUCCESS = "FAVORITE_LIST_SUCCESS";
export const FAVORITE_LIST_FAIL = "FAVORITE_LIST_FAIL";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
